import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";

export default function EventManagement() {
  const [clients, setClients] = useState<any[]>([]); const [events, setEvents] = useState<any[]>([]); const [message, setMessage] = useState("");
  const [form, setForm] = useState({ id: "", clientId: "", title: "", description: "", ticketPrice: "250000", paystackSubaccountCode: "" });
  async function load() { const [c, e] = await Promise.all([fetch("/api/management/clients"), fetch("/api/management/events")]); const cj = await c.json(); const ej = await e.json(); setClients(cj.clients || []); setEvents(ej.events || []); }
  useEffect(() => { void load(); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setMessage(""); const response = await fetch("/api/management/events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, ticketPrice: Number(form.ticketPrice) }) }); const body = await response.json(); if (!response.ok) { setMessage(body.error || "Unable to create event"); return; } setMessage("Event created"); setForm({ id: "", clientId: "", title: "", description: "", ticketPrice: "250000", paystackSubaccountCode: "" }); await load(); }
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-indigo-600">Event operations</p><h2 className="mt-1 text-2xl font-semibold">Create a live event</h2><p className="mt-1 text-sm text-slate-500">Leave the payout code empty to use your configured owner fallback.</p></div><form onSubmit={submit} className="grid gap-3 rounded-2xl bg-white p-6 shadow-sm sm:grid-cols-2"><input required placeholder="Event ID" value={form.id} onChange={e => setForm({ ...form, id: e.target.value })} className="h-10 rounded-lg border px-3" /><select required value={form.clientId} onChange={e => setForm({ ...form, clientId: e.target.value })} className="h-10 rounded-lg border px-3"><option value="">Select client</option>{clients.map(c => <option key={c.id} value={c.id}>{c.businessName}</option>)}</select><input required placeholder="Event title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className="h-10 rounded-lg border px-3" /><input required type="number" min="1" placeholder="Price in cents" value={form.ticketPrice} onChange={e => setForm({ ...form, ticketPrice: e.target.value })} className="h-10 rounded-lg border px-3" /><input placeholder="ACCT_ override (optional)" value={form.paystackSubaccountCode} onChange={e => setForm({ ...form, paystackSubaccountCode: e.target.value })} className="h-10 rounded-lg border px-3 sm:col-span-2" /><textarea placeholder="Description" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className="min-h-24 rounded-lg border p-3 sm:col-span-2" /><Button type="submit" className="sm:col-span-2">Create event</Button>{message && <p className="text-sm text-slate-600 sm:col-span-2">{message}</p>}</form><div className="space-y-3">{events.map(e => <div key={e.id} className="rounded-xl border bg-white p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{e.title}</p><p className="text-sm text-slate-500">{e.id} · {e.clientId}</p></div><span className="font-mono text-xs text-indigo-700">{e.paystackSubaccountCode}</span></div><p className="mt-2 text-sm text-slate-500">Customer link: /event/{e.id}</p></div>)}</div></div>;
}
