import { Button } from "@/components/ui/button";
import { ArrowLeft, CalendarDays, CheckCircle2, Download, Loader2, MapPin, Ticket as TicketIcon, XCircle } from "lucide-react";
import QRCode from "react-qr-code";
import { useEffect, useState } from "react";
import { Link, useRoute } from "wouter";

type TicketData = { id: string; status: "valid" | "used"; orderId?: string; buyerEmail?: string; buyerName?: string; eventTitle?: string; eventId?: string; eventDate?: string | null; venue?: string | null };
export default function TicketPage() {
  const [, params] = useRoute("/ticket/:id");
  const id = params?.id || "";
  const [ticket, setTicket] = useState<TicketData | null>(id.startsWith("preview-") ? { id, status: "valid", orderId: "preview-order" } : null);
  const [loading, setLoading] = useState(!id.startsWith("preview-"));
  const [error, setError] = useState("");
  useEffect(() => { if (!id || id.startsWith("preview-")) return; let active = true; fetch(`/api/tickets/${encodeURIComponent(id)}`).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "Ticket not found"); if (active) setTicket(data.ticket); }).catch(reason => active && setError(reason instanceof Error ? reason.message : "Ticket not found")).finally(() => active && setLoading(false)); return () => { active = false; }; }, [id]);
  const baseUrl = import.meta.env.VITE_PUBLIC_BASE_URL || import.meta.env.NEXT_PUBLIC_BASE_URL || import.meta.env.VITE_BASE_URL || window.location.origin;
  const verifyUrl = `${baseUrl.replace(/\/$/, "")}/gate-checkin-x9k2?ticket=${encodeURIComponent(ticket?.id || id)}`;
  if (loading) return <div className="grid min-h-screen place-items-center bg-slate-950 text-white"><Loader2 className="h-8 w-8 animate-spin text-indigo-300" /></div>;
  if (error || !ticket) return <div className="grid min-h-screen place-items-center bg-slate-950 px-5 text-center text-white"><div><TicketIcon className="mx-auto h-10 w-10 text-indigo-300" /><h1 className="mt-5 text-2xl font-semibold">Ticket unavailable</h1><p className="mt-2 text-slate-400">{error || "This ticket could not be loaded."}</p><Link href="/" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-indigo-300"><ArrowLeft className="h-4 w-4" /> Back to event</Link></div></div>;
  const isValid = ticket.status === "valid";
  return <div className="min-h-screen bg-slate-950 px-5 py-8 text-white sm:px-8"><div className="mx-auto max-w-lg"><Link href="/" className="mb-8 inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft className="h-4 w-4" /> Back to event</Link><div id="digital-ticket" className="overflow-hidden rounded-[2rem] bg-white text-slate-950 shadow-2xl"><div className="bg-indigo-600 px-7 pb-7 pt-8 text-white"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-sm font-semibold"><TicketIcon className="h-5 w-5" /> Passage</span><span className="rounded-full bg-white/15 px-3 py-1 text-xs font-semibold">GENERAL ADMISSION</span></div><h1 className="mt-10 text-3xl font-semibold tracking-tight">{ticket.eventTitle || "Your Passage event"}</h1><p className="mt-2 text-indigo-100">{ticket.buyerName || ticket.buyerEmail || "Your digital pass is ready."}</p></div><div className="relative px-7 py-8"><div className="absolute -top-3 left-0 h-6 w-6 -translate-x-1/2 rounded-full bg-slate-950" /><div className="absolute -top-3 right-0 h-6 w-6 translate-x-1/2 rounded-full bg-slate-950" /><div className="flex justify-center rounded-2xl bg-slate-50 p-5"><QRCode value={verifyUrl} size={210} bgColor="#f8fafc" fgColor="#0f172a" /></div><div className="mt-8 grid grid-cols-2 gap-y-6 border-b border-dashed border-slate-200 pb-7"><div><p className="text-xs uppercase tracking-wider text-slate-400">Date</p><p className="mt-1 text-sm font-semibold">{ticket.eventDate || "Date to be announced"}</p></div><div><p className="text-xs uppercase tracking-wider text-slate-400">Venue</p><p className="mt-1 text-sm font-semibold">{ticket.venue || "Venue to be announced"}</p></div><div><p className="text-xs uppercase tracking-wider text-slate-400">Ticket ID</p><p className="mt-1 font-mono text-sm font-semibold">{ticket.id}</p></div><div><p className="text-xs uppercase tracking-wider text-slate-400">Status</p><p className={`mt-1 flex items-center gap-1 text-sm font-semibold ${isValid ? "text-emerald-600" : "text-slate-500"}`}>{isValid ? <CheckCircle2 className="h-4 w-4" /> : <XCircle className="h-4 w-4" />} {isValid ? "Valid" : "Used"}</p></div></div><p className="mt-6 text-center text-xs leading-5 text-slate-400">{isValid ? "Present this QR code at the entrance. It can only be verified once." : "This ticket was already scanned and cannot be reused."}</p></div></div><div className="mt-5 flex gap-3"><Button onClick={() => window.print()} className="h-12 flex-1 gap-2 rounded-xl bg-white text-slate-950 hover:bg-slate-100"><Download className="h-4 w-4" /> Save ticket</Button><Link href={`/verify/${ticket.id}`} className="flex h-12 flex-1 items-center justify-center gap-2 rounded-xl border border-white/15 text-sm font-semibold text-white hover:bg-white/10"><MapPin className="h-4 w-4" /> Verify pass</Link></div><p className="mt-6 text-center text-xs text-slate-500">Keep this page available offline before you arrive.</p></div></div>;
}
