import { Button } from "@/components/ui/button";
import { ArrowLeft, CalendarDays, CheckCircle2, Download, MapPin, Ticket as TicketIcon } from "lucide-react";
import QRCode from "react-qr-code";
import { Link, useRoute } from "wouter";

export default function TicketPage() {
  const [, params] = useRoute("/ticket/:id");
  const id = params?.id || "preview-ticket";
  const verifyUrl = `${window.location.origin}/verify/${id}`;
  return <div className="min-h-screen bg-slate-950 px-5 py-8 text-white sm:px-8"><div className="mx-auto max-w-lg"><Link href="/" className="mb-8 inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft className="h-4 w-4" /> Back to event</Link><div id="digital-ticket" className="overflow-hidden rounded-[2rem] bg-white text-slate-950 shadow-2xl"><div className="bg-indigo-600 px-7 pb-7 pt-8 text-white"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-sm font-semibold"><TicketIcon className="h-5 w-5" /> Passage</span><span className="rounded-full bg-white/15 px-3 py-1 text-xs font-semibold">GENERAL ADMISSION</span></div><h1 className="mt-10 text-3xl font-semibold tracking-tight">The night belongs to you.</h1><p className="mt-2 text-indigo-100">Your digital pass is ready.</p></div><div className="relative px-7 py-8"><div className="absolute -top-3 left-0 h-6 w-6 -translate-x-1/2 rounded-full bg-slate-950" /><div className="absolute -top-3 right-0 h-6 w-6 translate-x-1/2 rounded-full bg-slate-950" /><div className="flex justify-center rounded-2xl bg-slate-50 p-5"><QRCode value={verifyUrl} size={210} bgColor="#f8fafc" fgColor="#0f172a" /></div><div className="mt-8 grid grid-cols-2 gap-y-6 border-b border-dashed border-slate-200 pb-7"><div><p className="text-xs uppercase tracking-wider text-slate-400">Date</p><p className="mt-1 text-sm font-semibold">12 October 2026</p></div><div><p className="text-xs uppercase tracking-wider text-slate-400">Venue</p><p className="mt-1 text-sm font-semibold">The Rooftop, Lagos</p></div><div><p className="text-xs uppercase tracking-wider text-slate-400">Ticket ID</p><p className="mt-1 font-mono text-sm font-semibold">{id}</p></div><div><p className="text-xs uppercase tracking-wider text-slate-400">Status</p><p className="mt-1 flex items-center gap-1 text-sm font-semibold text-emerald-600"><CheckCircle2 className="h-4 w-4" /> Valid</p></div></div><p className="mt-6 text-center text-xs leading-5 text-slate-400">Present this QR code at the entrance. It can only be verified once.</p></div></div><div className="mt-5 flex gap-3"><Button onClick={() => window.print()} className="h-12 flex-1 gap-2 rounded-xl bg-white text-slate-950 hover:bg-slate-100"><Download className="h-4 w-4" /> Save ticket</Button><Link href={`/verify/${id}`} className="flex h-12 flex-1 items-center justify-center gap-2 rounded-xl border border-white/15 text-sm font-semibold text-white hover:bg-white/10"><MapPin className="h-4 w-4" /> Verify pass</Link></div><p className="mt-6 text-center text-xs text-slate-500">Keep this page available offline before you arrive.</p></div></div>;
}
